---
# tasks file for smb.conf
- name: Check smb.conf.bak is exists
  stat:
    path: "{{ smb_conf_path }}/smb.conf.bak"
  register: smb_conf_bak

- name: Make backup from smb.conf
  ansible.builtin.copy:
    src: "{{ smb_conf_path }}/smb.conf"
    dest: "{{ smb_conf_path }}/smb.conf.bak"
    remote_src: yes
  register: smb_backup_state
  when: smb_conf_bak.stat.exists == False

- name: Clear out smb.conf
  ansible.builtin.shell: >
    echo "" > "{{ smb_conf_path }}/smb.conf"
  when: smb_backup_state.changed

- name: Set allowed hosts and shares
  blockinfile:
    path: "{{ smb_conf_path }}/smb.conf"
    block: |
      allow hosts = {{ allowed_hosts }}

      [NAS]
      comment = nas share
      browseable = yes
      path = {{ nas }}
      guest ok = no
      read only = no

      [vdx]
      comment = vdx share
      browseable = yes
      path = {{ vdx }}
      guest ok = no
      read only = no
  when: smb_backup_state.changed
  notify: restart_smbd