---
# tasks file for set grub.conf
- name: Set grub.conf
  ansible.builtin.lineinfile:
    path: "{{ grub_path }}/grub"
    regexp: '^GRUB_CMDLINE_LINUX=""'
    line: 'GRUB_CMDLINE_LINUX="{{ grub_cmdline_settings_part1 }} vfio-pci.ids={{ nv_vga_controller }},{{ nv_audio_device }},{{ nec_usb_controller_pci }},{{ asmedia_usb_controller_mb }},{{ intel_usb_controller_mb }} {{ disable_vga }} {{ grub_cmdline_settings_part2 }}"'
  register: grub_result

- name: Update initramfs
  ansible.builtin.shell: >
    update-initramfs -u -k all
  when: grub_result.changed