---
# tasks file for pmx_passtrough
- include: repoes_updates.yml
- include: grub_conf.yml
- include: blacklist_conf.yml
- include: ignore_msrs_conf.yml
- include: vfio_conf.yml
- include: swapiness.yml
- include: disable_logs.yml
- include: remove_subs_pop.yml