---
# tasks file for pmx_passtrough
- include: blacklist_conf.yml
- include: ignore_msrs_conf.yml
- include: repoes_updates.yml
- include: remove_subs_pop.yml
- include: grub_conf.yml
- include: vfio_conf.yml

- name: Check 101 VM config is exists
  stat:
    path: "{{ vm_path }}/101.conf"
  register: vm_conf


