---
# tasks file for remove enterprise repo
- name: Remove pve-enterprise repo
  ansible.builtin.lineinfile:
    path: "{{ proxmox_ent_repo_path }}/pve-enterprise.list"
    regexp: '^deb {{ proxmox_ent_repo }} bullseye pve-enterprise'
    line: '# deb {{ proxmox_ent_repo }} bullseye pve-enterprise'

- name: Set pve-no-subscription repo
  ansible.builtin.lineinfile:
    path: "{{ proxmox_repo_path }}/sources.list"
    regexp: '^# deb {{ proxmox_no_sub_repo }} bullseye pve-no-subscription'
    line: 'deb {{ proxmox_no_sub_repo }} bullseye pve-no-subscription'

- name: Update cache if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade Proxmox VE
  apt:
    upgrade: dist

- name: Update LXC template repo
  ansible.builtin.shell: >
    pveam update