---
# tasks file for set vfio modules
- name: Set modules
  blockinfile:
    path: "{{ module_path }}"
    block: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  register: modules_result

- name: Update initramfs
  ansible.builtin.shell: >
    update-initramfs -u -k all
  when: modules_result.changed